---
- hosts: servera
  become: true
  tasks:
    - name: verificar archivo
      stat: 
        path: /root/123.txt
      register: file
    - name: debug
      debug: 
        var: file

    - name: si el archivo existe
      shell: echo "123" > /root/AABB.txt
      when: file.stat.exists == true
...
